# Generated by Django 4.0.6 on 2023-02-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionyear',
            name='slug',
        ),
    ]
